#
# bump-date.yml
# Bump the distribution date
#

name: Bump Distribution Date

on:
  push:
    branches:
    - master
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  bump_date:
    name: Bump Distribution Date
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Bump Distribution Date
      run: |
        # Inline Bump Script
        DIST=$( date +"%Y-%m-%d" )
        eval "sed -E -i 's/(#define +STRING_DISTRIBUTION_DATE) .*$/\1 \"$DIST\"/g' Marlin/src/inc/Version.h" && \
        git config user.name "${GITHUB_ACTOR}" && \
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
        git add . && \
        git commit -m "[cron] Bump distribution date ($DIST)" && \
        git push
