#
# test-builds.yml
# Do test builds to catch compile errors
#

name: CI

on:
  #pull_request:
  #  branches:
  #  - master
  #  paths-ignore:
  #  - config/**
  #  - data/**
  #  - docs/**
  #  - '**/*.md'
  push:
    branches:
    - master
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  build:
    name: Build all Environments
    if: github.repository == 'knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S'

    runs-on: ubuntu-latest

    steps:

    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
        platformio update

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - uses: actions/checkout@master

    - name: Run PlatformIO
      run: platformio run